version: '3'
services:
    nut_exporter:
        image: nut_exporter
        ports:
            - 9199:9199
        environment:
            # NUT specific connection
            NUT_EXPORTER_SERVER: "192.168.70.30"
            NUT_EXPORTER_USERNAME: "<__USERNAME__>"
            NUT_EXPORTER_PASSWORD: "<__PASSWORD__>"
            # empty = all variables
            NUT_EXPORTER_VARIABLES: ""
            NUT_EXPORTER_STATUSES: ""
            # Prometheus Exporter Configuration
            NUT_EXPORTER_METRICS_NAMESPACE: "network_ups_tools"
            NUT_EXPORTER_WEB_LISTEN_ADDRESS: ":9199"
            NUT_EXPORTER_WEB_TELEMETRY_PATH: "/ups_metrics"
            NUT_EXPORTER_WEB_EXPORTER_TELEMETRY_PATH: "/metrics"
            #NUT_EXPORTER_WEB_AUTH_USERNAME: ""
            #NUT_EXPORTER_WEB_TLS_CERTFILE: ""
            #NUT_EXPORTER_WEB_TLS_KEYFILE: ""
            #NUT_EXPORTER_PRINT_METRICS: ""
            

            
